name: openai-clip
channels:
  - conda-forge
  - defaults
dependencies:
  # Specify Python version
  - python=3.10
  
  # Core dependencies (Conda/Mamba packages)
  - numpy
  - pip  # Keep 'pip' here so the dependency manager is installed

  # Packages installed via pip
  - pip:
    # Use a single string item to pass the full pip install command, 
    # but excluding 'pip3 install' and 'python -m'
    - torch --index-url https://download.pytorch.org/whl/cu126
    - torchvision --index-url https://download.pytorch.org/whl/cu126
    - timm
    - transformers
    - nnunetv2
    # You can add other pip-only packages here if needed later